/*!

=========================================================
* Black Dashboard PRO React - v1.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard-pro-react
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from 'react';
// react plugin for creating vector maps
import { VectorMap } from 'react-jvectormap';
// reactstrap components
import { Card, CardHeader, CardBody, Row, Col } from 'reactstrap';

var mapData = {
  AF: 16.63,
  AL: 11.58,
  DZ: 158.97,
  AO: 85.81,
  AG: 1.1,
  AR: 351.02,
  AM: 8.83,
  AU: 1219.72,
  AT: 366.26,
  AZ: 52.17,
  BS: 7.54,
  BH: 21.73,
  BD: 105.4,
  BB: 3.96,
  BY: 52.89,
  BE: 461.33,
  BZ: 1.43,
  BJ: 6.49,
  BT: 1.4,
  BO: 19.18,
  BA: 16.2,
  BW: 12.5,
  BR: 2023.53,
  BN: 11.96,
  BG: 44.84,
  BF: 8.67,
  BI: 1.47,
  KH: 11.36,
  CM: 21.88,
  CA: 1563.66,
  CV: 1.57,
  CF: 2.11,
  TD: 7.59,
  CL: 199.18,
  CN: 5745.13,
  CO: 283.11,
  KM: 0.56,
  CD: 12.6,
  CG: 11.88,
  CR: 35.02,
  CI: 22.38,
  HR: 59.92,
  CY: 22.75,
  CZ: 195.23,
  DK: 304.56,
  DJ: 1.14,
  DM: 0.38,
  DO: 50.87,
  EC: 61.49,
  EG: 216.83,
  SV: 21.8,
  GQ: 14.55,
  ER: 2.25,
  EE: 19.22,
  ET: 30.94,
  FJ: 3.15,
  FI: 231.98,
  FR: 2555.44,
  GA: 12.56,
  GM: 1.04,
  GE: 11.23,
  DE: 3305.9,
  GH: 18.06,
  GR: 305.01,
  GD: 0.65,
  GT: 40.77,
  GN: 4.34,
  GW: 0.83,
  GY: 2.2,
  HT: 6.5,
  HN: 15.34,
  HK: 226.49,
  HU: 132.28,
  IS: 12.77,
  IN: 1430.02,
  ID: 695.06,
  IR: 337.9,
  IQ: 84.14,
  IE: 204.14,
  IL: 201.25,
  IT: 2036.69,
  JM: 13.74,
  JP: 5390.9,
  JO: 27.13,
  KZ: 129.76,
  KE: 32.42,
  KI: 0.15,
  KR: 986.26,
  UNDEFINED: 5.73,
  KW: 117.32,
  KG: 4.44,
  LA: 6.34,
  LV: 23.39,
  LB: 39.15,
  LS: 1.8,
  LR: 0.98,
  LY: 77.91,
  LT: 35.73,
  LU: 52.43,
  MK: 9.58,
  MG: 8.33,
  MW: 5.04,
  MY: 218.95,
  MV: 1.43,
  ML: 9.08,
  MT: 7.8,
  MR: 3.49,
  MU: 9.43,
  MX: 1004.04,
  MD: 5.36,
  MN: 5.81,
  ME: 3.88,
  MA: 91.7,
  MZ: 10.21,
  MM: 35.65,
  NA: 11.45,
  NP: 15.11,
  NL: 770.31,
  NZ: 138,
  NI: 6.38,
  NE: 5.6,
  NG: 206.66,
  NO: 413.51,
  OM: 53.78,
  PK: 174.79,
  PA: 27.2,
  PG: 8.81,
  PY: 17.17,
  PE: 153.55,
  PH: 189.06,
  PL: 438.88,
  PT: 223.7,
  QA: 126.52,
  RO: 158.39,
  RU: 1476.91,
  RW: 5.69,
  WS: 0.55,
  ST: 0.19,
  SA: 434.44,
  SN: 12.66,
  RS: 38.92,
  SC: 0.92,
  SL: 1.9,
  SG: 217.38,
  SK: 86.26,
  SI: 46.44,
  SB: 0.67,
  ZA: 354.41,
  ES: 1374.78,
  LK: 48.24,
  KN: 0.56,
  LC: 1,
  VC: 0.58,
  SD: 65.93,
  SR: 3.3,
  SZ: 3.17,
  SE: 444.59,
  CH: 522.44,
  SY: 59.63,
  TW: 426.98,
  TJ: 5.58,
  TZ: 22.43,
  TH: 312.61,
  TL: 0.62,
  TG: 3.07,
  TO: 0.3,
  TT: 21.2,
  TN: 43.86,
  TR: 729.05,
  TM: 0,
  UG: 17.12,
  UA: 136.56,
  AE: 239.65,
  GB: 2258.57,
  US: 14624.18,
  UY: 40.71,
  UZ: 37.72,
  VU: 0.72,
  VE: 285.21,
  VN: 101.99,
  YE: 30.02,
  ZM: 15.69,
  ZW: 5.57,
};

const countryListPortuguese = {
  AF: 'Afeganistão',
  AL: 'Albânia',
  DZ: 'Argélia',
  AS: 'Samoa Americana',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguila',
  AQ: 'Antártica',
  AG: 'Antigua e Barbuda',
  AR: 'Argentina',
  AM: 'Armênia',
  AW: 'Aruba',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Bélgica',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermudas',
  BT: 'Butão',
  BO: 'Bolívia',
  BA: 'Bósnia e Herzegovina',
  BW: 'Botswana',
  BV: 'Ilha Bouvet',
  BR: 'Brasil',
  IO: 'Território Britânico do Oceano Índico',
  BN: 'Brunei Darussalam',
  BG: 'Bulgária',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Camboja',
  CM: 'Camarões',
  CA: 'Canadá',
  KY: 'Ilhas Cayman',
  CF: 'República Centro-Africana',
  TD: 'Chade',
  CL: 'Chile',
  CN: 'China',
  CX: 'Ilha do Natal',
  CC: 'Ilhas Cocos',
  CO: 'Colômbia',
  KM: 'Comores',
  CD: 'República Democrática do Congo',
  CG: 'República do Congo',
  CK: 'Ilhas Cook',
  CR: 'Costa Rica',
  HR: 'Croácia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Chipre',
  CZ: 'Czechia',
  CI: 'Costa do Marfim',
  DK: 'Dinamarca',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'República Dominicana',
  EC: 'Equador',
  EG: 'Egito',
  SV: 'El Salvador',
  GQ: 'Guiné Equatorial',
  ER: 'Eritreia',
  EE: 'Estônia',
  SZ: 'Eswatini',
  ET: 'Etiópia',
  FK: 'Ilhas Falkland',
  FO: 'Ilhas Faroé',
  FJ: 'Fiji',
  FI: 'Finlândia',
  FR: 'França',
  GF: 'Guiana Francesa',
  PF: 'Polinésia Francesa',
  TF: 'Territórios Franceses do Sul',
  GA: 'Gabão',
  GM: 'Gâmbia',
  GE: 'Georgia',
  DE: 'Alemanha',
  GH: 'Gana',
  GI: 'Gibraltar',
  GR: 'Grécia',
  GL: 'Groenlândia',
  GD: 'Granada',
  GP: 'Guadalupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guiné',
  GW: 'Guiné-Bissau',
  GY: 'Guiana',
  HT: 'Haiti',
  HM: 'Ilha Heard e Ilhas McDonald',
  VA: 'Santa Sé',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungria',
  IS: 'Islândia',
  IN: 'Índia',
  ID: 'Indonésia',
  IR: 'Irã',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IM: 'Ilha de Man',
  IL: 'Israel',
  IT: 'Itália',
  JM: 'Jamaica',
  JP: 'Japão',
  JE: 'Jersey',
  JO: 'Jordânia',
  KZ: 'Cazaquistão',
  KE: 'Quênia',
  KI: 'Kiribati',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  KG: 'Quirguistão',
  LA: 'República Democrática Popular do Laos',
  LV: 'Letônia',
  LB: 'Líbano',
  LS: 'Lesoto',
  LR: 'Libéria',
  LY: 'Líbia',
  LI: 'Liechtenstein',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MO: 'Macau',
  MG: 'Madagáscar',
  MW: 'Malawi',
  MY: 'Malásia',
  MV: 'Maldivas',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Ilhas Marshall',
  MQ: 'Martinica',
  MR: 'Mauritânia',
  MU: 'Maurício',
  YT: 'Mayotte',
  MX: 'México',
  FM: 'Micronésia',
  MD: 'Moldávia',
  MC: 'Monaco',
  MN: 'Mongólia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Marrocos',
  MZ: 'Moçambique',
  MM: 'Mianmar',
  NA: 'Namíbia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Holanda',
  NC: 'Nova Caledônia',
  NZ: 'Nova Zelândia',
  NI: 'Nicarágua',
  NE: 'Níger',
  NG: 'Nigéria',
  NU: 'Niue',
  NF: 'Ilha Norfolk',
  MP: 'Ilhas Marianas do Norte',
  NO: 'Noruega',
  OM: 'Omã',
  PK: 'Paquistão',
  PW: 'Palau',
  PS: 'Palestina',
  PA: 'Panamá',
  PG: 'Papua Nova Guiné',
  PY: 'Paraguai',
  PE: 'Peru',
  PH: 'Filipinas',
  PN: 'Pitcairn',
  PL: 'Polônia',
  PT: 'Portugal',
  PR: 'Porto Rico',
  QA: 'Catar',
  MK: 'República da Macedônia do Norte',
  RO: 'Romênia',
  RU: 'Rússia',
  RW: 'Ruanda',
  RE: 'Reunião',
  BL: 'São Bartolomeu',
  SH: 'Santa Helena, Ascensão e Tristão da Cunha',
  KN: 'São Cristóvão e Neves',
  LC: 'Santa Lúcia',
  MF: 'Saint Martin',
  PM: 'São Pedro e Miquelon',
  VC: 'São Vicente e Granadinas',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'São Tomé e Príncipe',
  SA: 'Arábia Saudita',
  SN: 'Senegal',
  RS: 'Sérvia',
  SC: 'Seychelles',
  SL: 'Serra Leoa',
  SG: 'Cingapura',
  SX: 'Sint Maarten',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  SB: 'Ilhas Salomão',
  SO: 'Somália',
  XS: 'Somalilândia',
  ZA: 'África do Sul',
  GS: 'Ilhas Geórgia do Sul e Sandwich do Sul',
  SS: 'Sudão do Sul',
  ES: 'Espanha',
  LK: 'Sri Lanka',
  SD: 'Sudão',
  SR: 'Suriname',
  SJ: 'Svalbard e Jan Mayen',
  SE: 'Suécia',
  CH: 'Suíça',
  SY: 'República Árabe da Síria',
  TW: 'Taiwan',
  TJ: 'Tajiquistão',
  TZ: 'Tanzânia',
  TH: 'Tailândia',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad e Tobago',
  TN: 'Tunísia',
  TR: 'Turquia',
  TM: 'Turcomenistão',
  TC: 'Ilhas Turks e Caicos',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ucrânia',
  AE: 'Emirados Árabes Unidos',
  GB: 'Grã-Bretanha',
  UM: 'Ilhas Menores Distantes dos Estados Unidos',
  US: 'Estados Unidos da América',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Viet Nam',
  VG: 'Ilhas Virgens (britânicas)',
  VI: 'Ilhas Virgens (EUA)',
  WF: 'Wallis e Futuna',
  EH: 'Saara Ocidental',
  YE: 'Iémen',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue',
  AX: 'Ilhas Aland',
};
const VectorMapView = () => {
  return (
    <>
      <div className='content'>
        <Row>
          <Col md='12'>
            <Card className='card-plain'>
              <CardHeader>
                <h4 className='text-center map-title'>
                  World Map <br />
                  <small>
                    Looks great on any resolution.{' '}
                    <a
                      href='https://www.npmjs.com/package/react-jvectormap'
                      target='_blank'
                      rel='noopener noreferrer'
                    >
                      React wrapper component
                    </a>{' '}
                    of jQuery{' '}
                    <a
                      href='http://jvectormap.com/'
                      target='_blank'
                      rel='noopener noreferrer'
                    >
                      jVector Map
                    </a>{' '}
                    pluging.
                  </small>
                </h4>
                <br />
              </CardHeader>
              <CardBody>
                <div className='map map-big' id='worldMap'>
                  <VectorMap
                    map={'world_mill'}
                    backgroundColor='transparent'
                    zoomOnScroll={true}
                    containerStyle={{
                      width: '100%',
                      height: '420px',
                    }}
                    onRegionTipShow={function (e, el, code) {
                      el.html(
                        countryListPortuguese[code] +
                          '<br> (GDP - ' +
                          (mapData[code]
                            ? mapData[code]
                            : 'sem dados disponíveis') +
                          ')'
                      );
                    }}
                    regionStyle={{
                      initial: {
                        fill: '#e4e4e4',
                        'fill-opacity': 0.9,
                        stroke: 'none',
                        'stroke-width': 0,
                        'stroke-opacity': 0,
                      },
                    }}
                    series={{
                      regions: [
                        {
                          values: mapData,
                          scale: ['#AAAAAA', '#444444'],
                          normalizeFunction: 'polynomial',
                        },
                      ],
                    }}
                  />
                </div>
              </CardBody>
            </Card>
          </Col>
        </Row>
      </div>
    </>
  );
};

export default VectorMapView;
